#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC_1540)       += fpc_1540/
obj-$(CONFIG_FINGERPRINT_GOODIX_FOD)	+= goodix_fod/
obj-$(CONFIG_FINGERPRINT_GOODIX_FOD_G3S)     += goodix_fod_G3S/
